# Copyright 2015 Cobalt Speech Inc.
import os

Import('env')

base_files = [
    'detector_api.cpp',
    'detector.cpp',
    'audio_io.cpp',
    'vad_model.cpp',
    ]

cpp_flags = ['-Werror', '-Wall']
module_name = 'detector'
include_dirs = ['..',]
static_lib = env.CompileToLibraries(base_files, module_name, include_dirs, cpp_flags)
