##############################################################################
#
# File:         SConscript (directory: ./site_scons/site_tools)
# Date:         5-Oct-2007
# Author:       Hugh Secker-Walker
# Description:  Verify site-specific SCons tools
#
# Copyright 2007, The Johns Hopkins University.  All rights reserved.
#
##############################################################################

# standard Cobalt treatment of Python code
Import('env')
env.File('ProjectTools.py')
env.File('PyTools.py')
env.File('CppTools.py')
