Import('env')
import os

base_files = [
    'configset.cpp',
    'model_config.cpp',
    ]

cpp_flags = ['-Werror', '-Wall',]
include_dirs = ['..',]
module_name = 'config'
env.CompileToLibraries(base_files, module_name, include_dirs)

test_config = env.BuildExecutable('test_config', 'test_config.cpp', include_dirs, module_name, cpp_flags)
env.RunLogrefTest(test_config, 'test_config')
