# Copyright 2015 Cobalt Speech Inc.
import os

Import('env')

base_files = [
    'configset.cpp',
    ]

cpp_flags = ['-Werror', '-Wall', '-Wno-sign-compare', '-Wno-unused-local-typedefs',]
module_name = 'config'
include_dirs = ['..',]
static_lib = env.CompileToLibraries(base_files, module_name, include_dirs, cpp_flags)

'''
test_exe = env.BuildExecutable('test_config', 'test_configset.cpp', include_dirs, module_name, cpp_flags)
env.RunLogrefTest(test_exe, 'test_config')
'''